stages:
  train:
    cmd: python train.py
    deps:
    - fra.txt
    - train.py
    params:
    - params.py:
    outs:
    - s2s:
        checkpoint: true
    metrics:
    - results.json:
        cache: false
    plots:
    - results:
        cache: false
  unzip:
    cmd: unzip -p fra-eng.zip fra.txt > fra.txt
    deps:
    - fra-eng.zip
    outs:
    - fra.txt
