name: Tests

on: [push, pull_request]

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        pyv: ['3.8', '3.9', '3.10']

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.pyv }}
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ matrix.pyv }}
        cache: pip
        cache-dependency-path: setup.cfg

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pipeline
      run: dvc exp run

